In [37]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [38]:
df = pd.read_csv('startup data.csv')

In [39]:
df.shape

(923, 49)

In [40]:
df['labels'].value_counts()

labels
1    597
0    326
Name: count, dtype: int64

imbalance dataset ig lets use smote

In [41]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Unnamed: 0,923.0,5.722979e+02,3.335854e+02,1.000000,2.835000e+02,5.770000e+02,8.665000e+02,1.153000e+03
latitude,923.0,3.851744e+01,3.741497e+00,25.752358,3.738887e+01,3.777928e+01,4.073065e+01,5.933523e+01
longitude,923.0,-1.035392e+02,2.239417e+01,-122.756956,-1.221987e+02,-1.183740e+02,-7.721473e+01,1.805712e+01
labels,923.0,6.468039e-01,4.782221e-01,0.000000,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
age_first_funding_year,923.0,2.235630e+00,2.510449e+00,-9.046600,5.767000e-01,1.446600e+00,3.575350e+00,2.189590e+01
age_last_funding_year,923.0,3.931456e+00,2.967910e+00,-9.046600,1.669850e+00,3.528800e+00,5.560250e+00,2.189590e+01
age_first_milestone_year,771.0,3.055353e+00,2.977057e+00,-14.169900,1.000000e+00,2.520500e+00,4.686300e+00,2.468490e+01
age_last_milestone_year,771.0,4.754423e+00,3.212107e+00,-7.005500,2.411000e+00,4.476700e+00,6.753400e+00,2.468490e+01
relationships,923.0,7.710726e+00,7.265776e+00,0.000000,3.000000e+00,5.000000e+00,1.000000e+01,6.300000e+01
funding_rounds,923.0,2.310943e+00,1.390922e+00,1.000000,1.000000e+00,2.000000e+00,3.000000e+00,1.000000e+01
funding_total_usd,923.0,2.541975e+07,1.896344e+08,11000.000000,2.725000e+06,1.000000e+07,2.472500e+07,5.700000e+09
milestones,923.0,1.841820e+00,1.322632e+00,0.000000,1.000000e+00,2.000000e+00,3.000000e+00,8.000000e+00
is_CA,923.0,5.276273e-01,4.995068e-01,0.000000,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
is_NY,923.0,1.148429e-01,3.190051e-01,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
is_MA,923.0,8.992416e-02,2.862282e-01,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
is_TX,923.0,4.550379e-02,2.085193e-01,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
is_otherstate,923.0,2.210184e-01,4.151578e-01,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
is_software,923.0,1.657638e-01,3.720701e-01,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
is_web,923.0,1.560130e-01,3.630644e-01,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
is_mobile,923.0,8.559047e-02,2.799100e-01,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
is_enterprise,923.0,7.908992e-02,2.700254e-01,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
is_advertising,923.0,6.717226e-02,2.504558e-01,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
is_gamesvideo,923.0,5.633803e-02,2.306983e-01,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
is_ecommerce,923.0,2.708559e-02,1.624209e-01,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
is_biotech,923.0,3.683640e-02,1.884621e-01,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
is_consulting,923.0,3.250271e-03,5.694928e-02,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
is_othercategory,923.0,3.228602e-01,4.678233e-01,0.000000,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00
has_VC,923.0,3.261105e-01,4.690424e-01,0.000000,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00
has_angel,923.0,2.546046e-01,4.358749e-01,0.000000,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00
has_roundA,923.0,5.081257e-01,5.002050e-01,0.000000,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
has_roundB,923.0,3.921993e-01,4.885054e-01,0.000000,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00
has_roundC,923.0,2.329361e-01,4.229310e-01,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
has_roundD,923.0,9.967497e-02,2.997286e-01,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
avg_participants,923.0,2.838586e+00,1.874601e+00,1.000000,1.500000e+00,2.500000e+00,3.800000e+00,1.600000e+01
is_top500,923.0,8.093174e-01,3.930523e-01,0.000000,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00

In [42]:
df.isna().sum()

Unnamed: 0                    0
state_code                    0
latitude                      0
longitude                     0
zip_code                      0
id                            0
city                          0
Unnamed: 6                  493
name                          0
labels                        0
founded_at                    0
closed_at                   588
first_funding_at              0
last_funding_at               0
age_first_funding_year        0
age_last_funding_year         0
age_first_milestone_year    152
age_last_milestone_year     152
relationships                 0
funding_rounds                0
funding_total_usd             0
milestones                    0
state_code.1                  1
is_CA                         0
is_NY                         0
is_MA                         0
is_TX                         0
is_otherstate                 0
category_code                 0
is_software                   0
is_web                        0
is_mobile                     0
is_enterprise                 0
is_advertising                0
is_gamesvideo                 0
is_ecommerce                  0
is_biotech                    0
is_consulting                 0
is_othercategory              0
object_id                     0
has_VC                        0
has_angel                     0
has_roundA                    0
has_roundB                    0
has_roundC                    0
has_roundD                    0
avg_participants              0
is_top500                     0
status                        0
dtype: int64

In [43]:
df.columns

Index(['Unnamed: 0', 'state_code', 'latitude', 'longitude', 'zip_code', 'id',
       'city', 'Unnamed: 6', 'name', 'labels', 'founded_at', 'closed_at',
       'first_funding_at', 'last_funding_at', 'age_first_funding_year',
       'age_last_funding_year', 'age_first_milestone_year',
       'age_last_milestone_year', 'relationships', 'funding_rounds',
       'funding_total_usd', 'milestones', 'state_code.1', 'is_CA', 'is_NY',
       'is_MA', 'is_TX', 'is_otherstate', 'category_code', 'is_software',
       'is_web', 'is_mobile', 'is_enterprise', 'is_advertising',
       'is_gamesvideo', 'is_ecommerce', 'is_biotech', 'is_consulting',
       'is_othercategory', 'object_id', 'has_VC', 'has_angel', 'has_roundA',
       'has_roundB', 'has_roundC', 'has_roundD', 'avg_participants',
       'is_top500', 'status'],
      dtype='object')

In [44]:
df.head().T

,0,1,2,3,4
Unnamed: 0,1005,204,1001,738,1002
state_code,CA,CA,CA,CA,CA
latitude,42.35888,37.238916,32.901049,37.320309,37.779281
longitude,-71.05682,-121.973718,-117.192656,-122.05004,-122.419236
zip_code,92101,95032,92121,95014,94105
id,c:6669,c:16283,c:65620,c:42668,c:65806
city,San Diego,Los Gatos,San Diego,Cupertino,San Francisco
Unnamed: 6,NaN,NaN,San Diego CA 92121,Cupertino CA 95014,San Francisco CA 94105
name,Bandsintown,TriCipher,Plixi,Solidcore Systems,Inhale Digital
labels,1,1,1,1,0
founded_at,1/1/2007,1/1/2000,3/18/2009,1/1/2002,8/1/2010
closed_at,NaN,NaN,NaN,NaN,10/1/2012
first_funding_at,4/1/2009,2/14/2005,3/30/2010,2/17/2005,8/1/2010
last_funding_at,1/1/2010,12/28/2009,3/30/2010,4/25/2007,4/1/2012
age_first_funding_year,2.2493,5.126,1.0329,3.1315,0.0
age_last_funding_year,3.0027,9.9973,1.0329,5.3151,1.6685
age_first_milestone_year,4.6685,7.0055,1.4575,6.0027,0.0384
age_last_milestone_year,6.7041,7.0055,2.2055,6.0027,0.0384
relationships,3,9,5,5,2
funding_rounds,3,4,1,3,2
funding_total_usd,375000,40100000,2600000,40000000,1300000
milestones,3,1,2,1,1
state_code.1,CA,CA,CA,CA,CA
is_CA,1,1,1,1,1
is_NY,0,0,0,0,0
is_MA,0,0,0,0,0
is_TX,0,0,0,0,0
is_otherstate,0,0,0,0,0
category_code,music,enterprise,web,software,games_video
is_software,0,0,0,1,0
is_web,0,0,1,0,0
is_mobile,0,0,0,0,0
is_enterprise,0,1,0,0,0
is_advertising,0,0,0,0,0
is_gamesvideo,0,0,0,0,1
is_ecommerce,0,0,0,0,0
is_biotech,0,0,0,0,0
is_consulting,0,0,0,0,0
is_othercategory,1,0,0,0,0
object_id,c:6669,c:16283,c:65620,c:42668,c:65806
has_VC,0,1,0,0,1
has_angel,1,0,0,0,1
has_roundA,0,0,1,0,0
has_roundB,0,1,0,1,0
has_roundC,0,1,0,1,0
has_roundD,0,1,0,1,0
avg_participants,1.0,4.75,4.0,3.3333,1.0
is_top500,0,1,1,1,1
status,acquired,acquired,acquired,acquired,closed

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 923 entries, 0 to 922
Data columns (total 49 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Unnamed: 0                923 non-null    int64
 1   state_code                923 non-null    object
 2   latitude                  923 non-null    float64
 3   longitude                 923 non-null    float64
 4   zip_code                  923 non-null    object
 5   id                        923 non-null    object
 6   city                      923 non-null    object
 7   Unnamed: 6                430 non-null    object
 8   name                      923 non-null    object
 9   labels                    923 non-null    int64
 10  founded_at                923 non-null    object
 11  closed_at                 335 non-null    object
 12  first_funding_at          923 non-null    object
 13  last_funding_at           923 non-null    object
 14  age_first_funding_year    923 non-null    float64
 15  age_last_funding_year     923 non-null    float64
 16  age_first_milestone_year  771 non-null    float64
 17  age_last_milestone_year   771 non-null    float64
 18  relationships             923 non-null    int64
 19  funding_rounds            923 non-null    int64
 20  funding_total_usd         923 non-null    int64
 21  milestones                923 non-null    int64
 22  state_code.1              922 non-null    object
 23  is_CA                     923 non-null    int64
 24  is_NY                     923 non-null    int64
 25  is_MA                     923 non-null    int64
 26  is_TX                     923 non-null    int64
 27  is_otherstate             923 non-null    int64
 28  category_code             923 non-null    object
 29  is_software               923 non-null    int64
 30  is_web                    923 non-null    int64
 31  is_mobile                 923 non-null    int64
 32  is_enterprise             923 non-null    int64
 33  is_advertising            923 non-null    int64
 34  is_gamesvideo             923 non-null    int64
 35  is_ecommerce              923 non-null    int64
 36  is_biotech                923 non-null    int64
 37  is_consulting             923 non-null    int64
 38  is_othercategory          923 non-null    int64
 39  object_id                 923 non-null    object
 40  has_VC                    923 non-null    int64
 41  has_angel                 923 non-null    int64
 42  has_roundA                923 non-null    int64
 43  has_roundB                923 non-null    int64
 44  has_roundC                923 non-null    int64
 45  has_roundD                923 non-null    int64
 46  avg_participants          923 non-null    float64
 47  is_top500                 923 non-null    int64
 48  status                    923 non-null    object
dtypes: float64(7), int64(28), object(14)
memory usage: 353.5+ KB

In [46]:
df['funding_total_usd'].value_counts().sort_index(ascending=False).head(20)

funding_total_usd
5700000000    1
510000000     1
299500000     1
238209999     1
232000100     1
211403000     1
162264126     1
148000000     1
142000000     1
135826373     1
129677153     1
125250000     1
125000000     1
122500000     1
122000000     1
121500000     1
108900000     1
100000000     1
98170000      1
90000000      1
Name: count, dtype: int64

In [47]:
drop_cols = [
    "Unnamed: 0", "Unnamed: 6", "id", "object_id", "name",   # junk IDs, no signal
    "zip_code", "latitude", "longitude", "city", "state_code.1",  # redundant with is_CA/is_NY/etc dummies
    "closed_at",          # LEAKAGE — only exists when company already closed
    "category_code",      # redundant — same info as is_software/is_web/etc dummies
    "founded_at", "first_funding_at", "last_funding_at"  # redundant with age_first/age_last_funding_year
]
df = df.drop(columns=[c for c in drop_cols if c in df.columns])

In [48]:
df['status']

0      acquired
1      acquired
2      acquired
3      acquired
4        closed
         ...
918    acquired
919      closed
920      closed
921    acquired
922    acquired
Name: status, Length: 923, dtype: object

In [49]:
df["target"] = df["status"].apply(lambda x: 1 if str(x).lower() != "closed" else 0)
df = df.drop(columns=["status"])

In [50]:
df["has_milestone"] = df["age_first_milestone_year"].notnull().astype(int)
df["age_first_milestone_year"] = df["age_first_milestone_year"].fillna(0)
df["age_last_milestone_year"] = df["age_last_milestone_year"].fillna(0)

In [51]:
#LOG-TRANSFORM funding
df["funding_total_usd_log"] = np.log1p(df["funding_total_usd"])

In [52]:
df = df.fillna(0)

['state_code', 'labels', 'age_first_funding_year', 'age_last_funding_year', 'age_first_milestone_year', 'age_last_milestone_year', 'relationships', 'funding_rounds', 'funding_total_usd', 'milestones', 'is_CA', 'is_NY', 'is_MA', 'is_TX', 'is_otherstate', 'is_software', 'is_web', 'is_mobile', 'is_enterprise', 'is_advertising', 'is_gamesvideo', 'is_ecommerce', 'is_biotech', 'is_consulting', 'is_othercategory', 'has_VC', 'has_angel', 'has_roundA', 'has_roundB', 'has_roundC', 'has_roundD', 'avg_participants', 'is_top500', 'target', 'has_milestone', 'funding_total_usd_log']

In [58]:
df["target"].value_counts()

target
0    923
Name: count, dtype: int64